// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateRoleRequestBodyRoleRoleUsersAttributes struct {
	UserID *int64 `json:"user_id,omitempty"`
}

type CreateRoleRequestBodyRole struct {
	Name                string                                         `json:"name"`
	RoleUsersAttributes []CreateRoleRequestBodyRoleRoleUsersAttributes `json:"role_users_attributes,omitempty"`
}

type CreateRoleRequestBody struct {
	Role CreateRoleRequestBodyRole `json:"role"`
}

type CreateRoleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
