// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateEndpointRequestBodyEndpoint struct {
	Events    []string `json:"events"`
	Filters   []string `json:"filters,omitempty"`
	TargetURL string   `json:"target_url"`
	Token     *string  `json:"token,omitempty"`
}

type CreateEndpointRequestBody struct {
	Endpoint CreateEndpointRequestBodyEndpoint `json:"endpoint"`
}

type CreateEndpointResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
