// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateStockRequestRequestBodyStockRequest struct {
	Email string `json:"email"`
	Sku   string `json:"sku"`
}

type CreateStockRequestRequestBody struct {
	StockRequest CreateStockRequestRequestBodyStockRequest `json:"stock_request"`
}

type CreateStockRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
