// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateSubscriptionTagsRequestBody struct {
	Tags []string `json:"tags,omitempty"`
}

type CreateSubscriptionTagsRequest struct {
	RequestBody    *CreateSubscriptionTagsRequestBody `request:"mediaType=application/json"`
	SubscriptionID string                             `pathParam:"style=simple,explode=false,name=subscription_id"`
}

type CreateSubscriptionTagsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
