// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateTagRequestBodyTag struct {
	Name string `json:"name"`
}

type CreateTagRequestBody struct {
	Tag CreateTagRequestBodyTag `json:"tag"`
}

type CreateTagResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
