// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIWebhookEndpointsIDRequest struct {
	// Endpoint id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteAPIWebhookEndpointsIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
