// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FindWebhookAttempsRequest struct {
	// Ransack search
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type FindWebhookAttempsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
