// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FindWebhookEndpointsRequest struct {
	// Maximum number of attempts (by default limited to 25)
	AttemptsCount *int64 `queryParam:"style=form,explode=true,name=attempts_count"`
	// Include attemps
	IncludeAttempts *bool `queryParam:"style=form,explode=true,name=include_attempts"`
	// Ransack search
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type FindWebhookEndpointsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
