// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type FindRemindersQueryParams struct {
	// Ransack search
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type FindRemindersRequest struct {
	QueryParams FindRemindersQueryParams
}

type FindRemindersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
