// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIWebhookEndpointsIDRequest struct {
	// Maximum number of attempts (by default limited to 25)
	AttemptsCount *int64 `queryParam:"style=form,explode=true,name=attempts_count"`
	// Endpoint id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Include attemps
	IncludeAttempts *bool `queryParam:"style=form,explode=true,name=include_attempts"`
}

// GetAPIWebhookEndpointsID200ApplicationJSON - Found
type GetAPIWebhookEndpointsID200ApplicationJSON struct {
	Events    []string `json:"events,omitempty"`
	Filters   []string `json:"filters,omitempty"`
	ID        *int64   `json:"id,omitempty"`
	TargetURL *string  `json:"target_url,omitempty"`
	Token     *string  `json:"token,omitempty"`
}

type GetAPIWebhookEndpointsIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Found
	GetAPIWebhookEndpointsID200ApplicationJSONObject *GetAPIWebhookEndpointsID200ApplicationJSON
}
