// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIStoresStoreIDEnvironmentVariablesRequest struct {
	StoreID int64 `pathParam:"style=simple,explode=false,name=store_id"`
}

// GetAPIStoresStoreIDEnvironmentVariables200ApplicationJSON - The Environment Variables of the Store
type GetAPIStoresStoreIDEnvironmentVariables200ApplicationJSON struct {
	Config1 *string `json:"CONFIG_1,omitempty"`
	Config2 *string `json:"CONFIG_2,omitempty"`
}

type GetAPIStoresStoreIDEnvironmentVariablesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetAPIStoresStoreIDEnvironmentVariables200ApplicationJSONObject *GetAPIStoresStoreIDEnvironmentVariables200ApplicationJSON
}
