// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchAPIStoresStoreIDEnvironmentVariablesRequestBodySettings struct {
	Delete *bool  `json:"_delete,omitempty"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type PatchAPIStoresStoreIDEnvironmentVariablesRequestBody struct {
	Settings []PatchAPIStoresStoreIDEnvironmentVariablesRequestBodySettings `json:"settings"`
}

type PatchAPIStoresStoreIDEnvironmentVariablesRequest struct {
	RequestBody *PatchAPIStoresStoreIDEnvironmentVariablesRequestBody `request:"mediaType=application/json"`
	StoreID     int64                                                 `pathParam:"style=simple,explode=false,name=store_id"`
}

// PatchAPIStoresStoreIDEnvironmentVariables201ApplicationJSON - The updated Environment Variables of the Store
type PatchAPIStoresStoreIDEnvironmentVariables201ApplicationJSON struct {
	Config1 *string `json:"CONFIG_1,omitempty"`
	Config2 *string `json:"CONFIG_2,omitempty"`
}

type PatchAPIStoresStoreIDEnvironmentVariablesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	PatchAPIStoresStoreIDEnvironmentVariables201ApplicationJSONObject *PatchAPIStoresStoreIDEnvironmentVariables201ApplicationJSON
}
