// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPISolidusImporterImportsRequestBody struct {
	Content     []byte `multipartForm:"content"`
	RequestBody string `multipartForm:"name=requestBody"`
}

type PostAPISolidusImporterImportsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
