// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIStoresStoreIDEnvironmentVariablesRequestBodySettings struct {
	Delete *bool  `json:"_delete,omitempty"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type PostAPIStoresStoreIDEnvironmentVariablesRequestBody struct {
	Settings []PostAPIStoresStoreIDEnvironmentVariablesRequestBodySettings `json:"settings"`
}

type PostAPIStoresStoreIDEnvironmentVariablesRequest struct {
	RequestBody *PostAPIStoresStoreIDEnvironmentVariablesRequestBody `request:"mediaType=application/json"`
	StoreID     int64                                                `pathParam:"style=simple,explode=false,name=store_id"`
}

// PostAPIStoresStoreIDEnvironmentVariables201ApplicationJSON - The updated Environment Variables of the Store
type PostAPIStoresStoreIDEnvironmentVariables201ApplicationJSON struct {
	Config1 *string `json:"CONFIG_1,omitempty"`
	Config2 *string `json:"CONFIG_2,omitempty"`
}

type PostAPIStoresStoreIDEnvironmentVariablesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	PostAPIStoresStoreIDEnvironmentVariables201ApplicationJSONObject *PostAPIStoresStoreIDEnvironmentVariables201ApplicationJSON
}
