// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPITagsRemoveFromOrderNumberRequestBody struct {
	Tags []string `json:"tags,omitempty"`
}

type PutAPITagsRemoveFromOrderNumberRequest struct {
	RequestBody *PutAPITagsRemoveFromOrderNumberRequestBody `request:"mediaType=application/json"`
	OrderNumber string                                      `pathParam:"style=simple,explode=false,name=order_number"`
}

type PutAPITagsRemoveFromOrderNumberResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
