// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIRolesIDRequestBodyRoleUsers struct {
	Destroy *bool `json:"_destroy,omitempty"`
	ID      int64 `json:"id"`
}

type PutAPIRolesIDRequestBodyRole struct {
	Name  string                              `json:"name"`
	Users []PutAPIRolesIDRequestBodyRoleUsers `json:"users,omitempty"`
}

type PutAPIRolesIDRequestBody struct {
	Role PutAPIRolesIDRequestBodyRole `json:"role"`
}

type PutAPIRolesIDRequest struct {
	RequestBody *PutAPIRolesIDRequestBody `request:"mediaType=application/json"`
	// Role id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type PutAPIRolesIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
